framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(CACHE_DSN)%'
        pools:
            cache.fund_transfer:
                adapter: cache.app
                default_lifetime: 3600
